### ISSUE TITLE
High severity security vulnerability in dot-prop

### ISSUE THREAD

**Issue by christiansaiki** [avohq/avo#13]
I'm getting the error from:
`avo > update-notifier > configstore > dot-prop` and `avo > configstore > dot-prop`

https://www.npmjs.com/advisories/1213

Can you please release new version that patches this vulns?
Thanks

**Comment by logason** [comment]
Thank you for reporting @christiansaiki! This issue has been resolved in `avo@2.0.0`, including the changes from #36 and #37
