### ISSUE TITLE
Connection errors - import and object this

### ISSUE THREAD

**Issue by abz-denys-z** [avohq/avo#226]
Hi

When connecting Avo( For Web) I get two errors:

1. Import-related Avo configuration file, which I got with the **avo pull** command + also copied from the website during initialisation - [https://scr.abz.agency/yAuA5YrK](https://scr.abz.agency/yAuA5YrK)
2. With this which is **undefined** - [https://scr.abz.agency/P8uNAyxd](https://scr.abz.agency/P8uNAyxd) / [https://scr.abz.agency/P8uNAyjw](https://scr.abz.agency/P8uNAyjw)

I used dependencies 

avo: 3.2.6
mixpanel-browser: 2.45.0

**Comment by hugihlynsson** [comment]
Hi Denys! As this is a Codegen related issue I'd love to move this discussion to the Avo chat. I'll ping you there.
