### ISSUE TITLE
Have to use `sudo`

### ISSUE THREAD

**Issue by JurajBegovac** [avohq/avo#243]
Hello,

I have more of a question than an issue. 
Whenever I try to use the command `npm install -g avo` I need to use `sudo` which means that all subsequent avo commands also need to be run with `sudo`. 
Consequently, all files downloaded using the avo CLI are owned by the root owner, which makes it impossible for me to modify them. 

What should I do in this case? Is this behavior intentional?

Thanks in advance

**Comment by bragur** [comment]
Hey Juraj, have you experienced similar issues with other global packages? This behavior is not expected, and I haven't encountered it before. It's possible that your permissions may have been altered in some way. I stumbled upon a [related thread](https://stackoverflow.com/questions/20114901/why-does-npm-need-sudo-for-everything) that may shed some light on the situation.

To unblock you now, a potential solution would be to include `avo` in your project and use it locally within the project.

**Comment by JurajBegovac** [comment]
Hello,

Yes, I modified the permissions of the npm and /.config files using the `chown` command.
