### ISSUE TITLE
Found 4 moderate severity vulnerabilities

### ISSUE THREAD

**Issue by EddSuarez** [avohq/avo#41]
Paths:

- ` avo > inquirer-fuzzy-path > inquirer > string-width >   strip-ansi > ansi-regex ` 
- ` avo > inquirer-fuzzy-path > inquirer > strip-ansi > ansi-regex `
- ` avo > yurnalist > strip-ansi > ansi-regex ` 
- ` avo > inquirer-fuzzy-path > strip-ansi > ansi-regex `

https://github.com/advisories/GHSA-93q8-gq69-wqmw

Could you release new version with this vulnerabilities fixed? 🙏🏻  

thanks in advance

**Comment by hugihlynsson** [comment]
Hi @EddSuarez! We've just updated the dependencies and resolved all known vulnerabilities. We'll be releasing avo version 3.0.0 soon.

**Comment by hugihlynsson** [comment]
@EddSuarez we've released version 3.0.0-beta1 that includes a handful of security updates. It would be fantastic if you could try that out
